### ISSUE TITLE
Renommer correctement _tous_ les vols

### ISSUE THREAD

**Issue by davidp57** [VEAF/VEAF-Open-Training-Mission-Marianas#5]
Les hélicos doivent être :
 - en groupe de 1 pour les hélicos de transport (c'est aussi valable pour les Yak-52)
 - en groupe de 4 pour les autres
 
Les noms des groupes doivent être sous la forme : "<type> <lieu>-<index>" ; si l'appareil est en hot start on rajoute "-HOT" après le nom du lieu
 - <type> est le nom du type d'appareil (dans la liste "type")
 - <lieu> est le nom de l'endroit où il spawn
 - <index> est le numéro du flight _dans cet endroit_
Les noms des pilotes sont le nom du groupe suivi de -<index pilote>
Exemple :
 - "Ka-50 Olf Orote-1", composé de "Ka-50 Olf Orote-1-1", "Ka-50 Olf Orote-1-2", "Ka-50 Olf Orote-1-3" et "Ka-50 Olf Orote-1-4"
 - "Mi-24P Olf Orote-1", composé de "Mi-24P Olf Orote-1-1"
 - "Mi-8MTV2 Olf Orote-HOT-1", composé de "Mi-8MTV2 Olf Orote-HOT-1-1"

**Comment by davidp57** [comment]
Note : ceci est valable pour __tous__ les vols d'appareils de transport, j'ai nommé : 
 - les Mi-8
 - les Mi-24
 - les Huey
 - les Yak-52
 - les C130

**Comment by MikcaelX** [comment]
Je peux pas fermé mais bon c'est fait !

**Comment by davidp57** [comment]
à tester mais si il dit que c'est fait ;)
